use tayani_data;


CREATE TABLE if not exists`DIESEL_BUYERS` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- Describe the table
DESCRIBE DIESEL_BUYERS;

INSERT INTO DIESEL_BUYERS VALUES (1, "Kahale");
INSERT INTO DIESEL_BUYERS VALUES (2, "Aggrawal");
INSERT INTO DIESEL_BUYERS VALUES (3, "Joseph");
INSERT INTO DIESEL_BUYERS VALUES (4, "Yadav");

